version: "3.1"

services:
  takethecontrol_postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: takethecontrol
    volumes:
      - takethecontrol_postgres:/var/lib/postgresql

volumes:
  takethecontrol_postgres:
